apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurite
  labels:
    app: azurite
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurite
  template:
    metadata:
      labels:
        app: azurite
    spec:
      containers:
        - name: azurite
          image: mcr.microsoft.com/azure-storage/azurite:latest
          imagePullPolicy: IfNotPresent
          args:
            - azurite
            - --blobHost
            - 0.0.0.0
            - --queueHost
            - 0.0.0.0
            - --tableHost
            - 0.0.0.0
            - --location
            - /data
            - --debug
            - /data/debug.log
          ports:
            - containerPort: 10000
            - containerPort: 10001
            - containerPort: 10002
          volumeMounts:
            - name: azurite-data
              mountPath: /data
      volumes:
        - name: azurite-data
          emptyDir: {}
