apiVersion: v1
kind: Secret
metadata:
  name: azurite-connection
type: Opaque
stringData:
  connection: "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=<YOUR AZURE ACCOUNT NAME>;AccountKey=<YOUR AZURE ACCOUNT KEY>;BlobEndpoint=https://<DOMAIN>.blob.core.windows.net/;FileEndpoint=https://<DOMAIN>.file.core.windows.net/;QueueEndpoint=https://prodconsdemost.queue.core.windows.net/;TableEndpoint=https://<DOMAIN>.table.core.windows.net/"
