apiVersion: v1
kind: Service
metadata:
  name: producer
spec:
  type: LoadBalancer   # Change from NodePort to LoadBalancer
  selector:
    app: producer
  ports:
  - port: 3000         # This is the port you'll access on localhost
    targetPort: 3000
    # No need for nodePort